- name: Verify signature on certificate
  ansible.builtin.command: >
    openssl verify
    -verbose
    -CAfile {{ ca_certs_dir }}/ca.crt
    {{ ca_certs_dir }}/{{ inventory_hostname }}.crt
  changed_when: false

- name: Verify signature on server certificate
  ansible.builtin.command: >
    openssl verify
    -verbose
    -CAfile {{ ca_certs_dir }}/ca.crt
    {{ ca_certs_dir }}/{{ inventory_hostname }}-server.crt
  changed_when: false

- name: Check if instance key is present
  ansible.builtin.stat:
    path: "{{ ca_certs_dir }}/{{ inventory_hostname }}.key"
  register: instance_key_stat

- name: Fail if instance key is missing
  ansible.builtin.fail:
    msg: "Instance key is missing"
  when:
    - not instance_key_stat.stat.exists | bool

- name: Check if Logstash key is present
  ansible.builtin.stat:
    path: "{{ ca_certs_dir }}/{{ inventory_hostname }}-pkcs8.key"
  register: logstash_key_stat

- name: Fail if Logstash key is missing
  ansible.builtin.fail:
    msg: "Logstash key is missing"
  when:
    - not logstash_key_stat.stat.exists | bool

- name: Verify signature on etcd peer certificate
  ansible.builtin.command: >
    openssl verify
    -verbose
    -CAfile {{ ca_certs_dir }}/ca.crt
    {{ ca_certs_dir }}/{{ inventory_hostname }}-etcd.crt
  changed_when: false

- name: Verify signature on etcd server certificate
  ansible.builtin.command: >
    openssl verify
    -verbose
    -CAfile {{ ca_certs_dir }}/ca.crt
    {{ ca_certs_dir }}/{{ inventory_hostname }}-etcd-server.crt
  changed_when: false

- name: Verify signature on etcd server certificate
  ansible.builtin.command: >
    openssl verify
    -verbose
    -CAfile {{ ca_certs_dir }}/ca.crt
    {{ ca_certs_dir }}/{{ inventory_hostname }}-etcd-server.crt
  changed_when: false

- name: Register SAN of etcd peer certificate
  ansible.builtin.command: >
    openssl x509
    -text -noout
    -in {{ ca_certs_dir }}/{{ inventory_hostname }}-etcd.crt
    -certopt "
    no_subject,
    no_header,
    no_version,
    no_serial,
    no_signame,
    no_validity,
    no_issuer,
    no_pubkey,
    no_sigdump,
    no_aux"
  register: etcd_san_peer_stat
  changed_when: false

- name: Register SAN of etcd server certificate
  ansible.builtin.command: >
    openssl x509
    -text
    -noout
    -in {{ ca_certs_dir }}/{{ inventory_hostname }}-etcd-server.crt
    -certopt "
    no_subject,
    no_header,
    no_version,
    no_serial,
    no_signame,
    no_validity,
    no_issuer,
    no_pubkey,
    no_sigdump,
    no_aux"
  register: etcd_san_server_stat
  changed_when: false

- name: Fail if SAN of etcd peer certificate is missing IP addresses
  ansible.builtin.fail:
    msg: "Default IPv4 address in etcd peer certifcate are missing"
  when:
    - hostvars['ca_default_client']['ansible_default_ipv4']['address']
      not in etcd_san_peer_stat.stdout
    - '"127.0.0.1" not in etcd_san_peer_stat.stdout'

- name: Fail if SAN of etcd server certificate is missing IP addresses
  ansible.builtin.fail:
    msg: "Default IPv4 address in etcd server certifcate are missing"
  when:
    - hostvars['ca_default_client']['ansible_default_ipv4']['address']
      not in etcd_san_server_stat.stdout
    - '"127.0.0.1" not in etcd_san_server_stat.stdout'
