---

###
# The following code checks for the OpenSSL version being used
# When signing a CA key, OpenSSL 3 needs paramaters older versions don't
# understand.
# The `version` filter is unkown to Jinja2 so we need a fact that helps
# with changing templates accordingly

- name: Get OpenSSL version
  ansible.builtin.command: openssl version
  register: _ca_openssl_version_raw
  changed_when: false

- name: Extract OpenSSL version string
  ansible.builtin.set_fact:
    _ca_openssl_version: "{{ _ca_openssl_version_raw.stdout.split(' ')[1] }}"

- name: Set OpenSSL extension parameters (OpenSSL ≥ 3.0)
  ansible.builtin.set_fact:
    _ca_openssl_ca_ext_opts: "-extensions v3_ca"
  when: _ca_openssl_version is version('3.0', '>=')

- name: Set OpenSSL extension parameters (OpenSSL < 3.0)
  ansible.builtin.set_fact:
    _ca_openssl_ca_ext_opts: ""
  when: _ca_openssl_version is version('3.0', '<')

- name: Set Variable for Jinja2 templates
  ansible.builtin.set_fact:
    _ca_ca_openssl_version_3: true
  when: _ca_openssl_version is version('3.0', '>=')
