---

- name: Verify
  hosts: all
  vars:
    ca_ca_dir: /opt/ca
  tasks:
  - name: Verify signature on certificate
    command: >
      openssl verify
      -verbose
      -CAfile {{ ca_ca_dir }}/ca.crt
      {{ ca_ca_dir }}/{{ ansible_hostname }}.crt
