---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    ca_ca_host: ca_default
    ca_ca_password: ChangeMe
    ca_logstash: true
    ca_etcd: true
    ca_etcd_group: molecule
    ca_ca_days: 3650
    ca_valid_time: +365d
    ca_check_valid_time: +1w
    ca_renew: true

  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        ca_ca_signing_key_algorithm: Ed25519
        ca_ca_dir: /opt/ca-ed25519
        ca_client_ca_dir: /opt/ca-ed25519
        ca_localdir: /tmp/ca-ed25519
