---
- name: Prepare
  hosts: all
  vars:
    ca_ca_host: ca_default
    ca_logstash: true
    ca_etcd: true
    ca_etcd_group: molecule
    ca_valid_time: "+5d"
    ca_renew: true
  tasks:

    - name: Install Python libraries
      pip:
        name: cryptography>= 1.2.3

    - name: Install packages for RHEL
      package:
        name:
          - iproute
          - NetworkManager
      when: ansible_os_family == "RedHat"

    - name: Start NetworkManager
      service:
        name: NetworkManager
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Gather facts again to define ansible_default_ipv4
      setup:

    - name: "Include CA role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
