- name: Verify signature on certificate
  command: >
    openssl verify
    -verbose
    -CAfile {{ ca_client_ca_dir }}/ca.crt
    {{ ca_client_ca_dir }}/{{ inventory_hostname }}.crt

- name: Verify signature on server certificate
  command: >
    openssl verify
    -verbose
    -CAfile {{ ca_client_ca_dir }}/ca.crt
    {{ ca_client_ca_dir }}/{{ inventory_hostname }}-server.crt

- name: Check if instance key is present
  stat:
    path: "{{ ca_client_ca_dir }}/{{ inventory_hostname }}.key"
  register: instance_key_stat

- name: Fail if instance key is missing
  fail:
    msg: "Instance key is missing"
  when:
    - not instance_key_stat.stat.exists | bool

- name: Check if Logstash key is present
  stat:
    path: "{{ ca_client_ca_dir }}/{{ inventory_hostname }}-pkcs8.key"
  register: logstash_key_stat

- name: Fail if Logstash key is missing
  fail:
    msg: "Logstash key is missing"
  when:
    - not logstash_key_stat.stat.exists | bool

- name: Verify signature on etcd peer certificate
  command: >
    openssl verify
    -verbose
    -CAfile {{ ca_client_ca_dir }}/ca.crt
    {{ ca_client_ca_dir }}/{{ inventory_hostname }}-etcd.crt

- name: Verify signature on etcd server certificate
  command: >
    openssl verify
    -verbose
    -CAfile {{ ca_client_ca_dir }}/ca.crt
    {{ ca_client_ca_dir }}/{{ inventory_hostname }}-etcd-server.crt

- name: Verify signature on etcd server certificate
  command: >
    openssl verify
    -verbose
    -CAfile {{ ca_client_ca_dir }}/ca.crt
    {{ ca_client_ca_dir }}/{{ inventory_hostname }}-etcd-server.crt

- name: Register SAN of etcd peer certificate
  command: >
    openssl x509
    -text
    -noout
    -in {{ ca_client_ca_dir }}/{{ inventory_hostname }}-etcd.crt
    -certopt "
    no_subject,
    no_header,
    no_version,
    no_serial,
    no_signame,
    no_validity,
    no_issuer,
    no_pubkey,
    no_sigdump,
    no_aux"
  register: etcd_san_peer_stat

- name: Register SAN of etcd server certificate
  command: >
    openssl x509
    -text
    -noout
    -in {{ ca_client_ca_dir }}/{{ inventory_hostname }}-etcd-server.crt
    -certopt "
    no_subject,
    no_header,
    no_version,
    no_serial,
    no_signame,
    no_validity,
    no_issuer,
    no_pubkey,
    no_sigdump,
    no_aux"
  register: etcd_san_server_stat

- name: Fail if SAN of etcd peer certificate is missing addresses
  fail:
    msg: "Default IPv4 address in etcd peer certifcate are missing"
  when:
    - hostvars['ca_default_client']['ansible_default_ipv4']['address']
      not in etcd_san_peer_stat.stdout
    - '"127.0.0.1" not in etcd_san_peer_stat.stdout'

- name: Fail if SAN of etcd server certificate is missing IP addresses
  fail:
    msg: "Default IPv4 address in etcd server certifcate are missing"
  when:
    - hostvars['ca_default_client']['ansible_default_ipv4']['address']
      not in etcd_san_server_stat.stdout
    - '"127.0.0.1" not in etcd_san_server_stat.stdout'

- name: Check if notAfter of client certificate is within {{ valid_days }} days
  command: >
    openssl x509
    -noout
    -checkend {{ valid_days * 24 * 60 * 60 - max_test_duration_seconds }}
    -in {{ ca_client_ca_dir }}/{{ inventory_hostname }}.crt

- name: Check if notAfter of server certificate is within {{ valid_days }} days
  command: >
    openssl x509
    -noout
    -checkend {{ valid_days * 24 * 60 * 60 - max_test_duration_seconds }}
    -in {{ ca_client_ca_dir }}/{{ inventory_hostname }}-server.crt

- name: Check if notAfter of etcd certificate is within {{ valid_days }} days
  command: >
    openssl x509
    -noout
    -checkend {{ valid_days * 24 * 60 * 60 - max_test_duration_seconds }}
    -in {{ ca_client_ca_dir }}/{{ inventory_hostname }}-etcd.crt

- name: Check if notAfter of etcd server certificate is within {{ valid_days }} days
  command: >
    openssl x509
    -noout
    -checkend {{ valid_days * 24 * 60 * 60 - max_test_duration_seconds }}
    -in {{ ca_client_ca_dir }}/{{ inventory_hostname }}-etcd-server.crt

- name: Check if notAfter of CA certificate is valid within {{ ca_ca_days }} days
  command: >
    openssl x509
    -noout
    -checkend {{ ca_ca_days * 24 * 60 * 60 - max_test_duration_seconds }}
    -in {{ ca_client_ca_dir }}/ca.crt

- name: Register if on certificate change handler has run for initial client certificate
  stat:
    path: "{{ ansible_env.HOME }}/{{ inventory_hostname }}.initial_certificate"
  register: initial_handler_file

- name: Fail if initial file of on certificate change handler does not exist
  fail:
    msg: "Failed because on certificate change handler hasn't created initial file"
  when: not initial_handler_file.stat.exists

- name: Register if on certificate change handler has run for renewed client certificate
  stat:
    path: "{{ ansible_env.HOME }}/{{ inventory_hostname }}.renewed_certificate"
  register: renewed_handler_file

- name: Fail if renewed file of on certificate change handler does not exist
  fail:
    msg: "Failed because on certificate change handler hasn't created renewed file"
  when: not renewed_handler_file.stat.exists
