---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  collections:
    - netways.elasticstack
  vars:
    ca_ca_host: ca_default
    ca_logstash: true
    ca_etcd: true
    ca_etcd_group: molecule
    ca_openssl_cipher: auto
    ca_ca_dir: /opt/logstash-ca
    logstash_certs_dir: /opt/logstash-ca
  tasks:
    - name: "Include CA role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

    - name: "Include Logstash role"
      include_role:
        name: logstash
