---
name: KICS Security Scan
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
  push:
    branches:
      - 'main'
  merge_group:
  schedule:
    - cron: '15 6 * * 4'
jobs:
  kics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: Checkmarx/kics-github-action@cd1f3774406f7818e3f79b77b093fe2ebaaf5c1d #v2.1.12
        with:
          # path: 'roles,plugins'
          path: '.'
          fail_on: high
          ignore_on_exit: results
          output_formats: 'json,sarif'
          output_path: results-dir
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@5378192d256ef1302a6980fffe5ca04426d43091 #v3.28.21
        with:
          sarif_file: results-dir/results.sarif
